import FourColor.Adjoin
import FourColor.Component
import FourColor.Seq
import FourColor.Path
import FourColor.Orbit
import FourColor.Color
import FourColor.Chromogram
import FourColor.Ctree
import FourColor.Gtree
import FourColor.CtreeRestrict
import FourColor.GtreeRestrict
import FourColor.KempeTree
import FourColor.Dyck
import FourColor.InitCtree
import FourColor.InitGtree
import FourColor.Perm
import FourColor.Hypermap
import FourColor.Walkup
import FourColor.Euler
import FourColor.Jordan
import FourColor.EulerTree
import FourColor.Coloring
import FourColor.Kempe
import FourColor.CfMap
import FourColor.Configurations
import FourColor.CfColor
import FourColor.CfQuiz
import FourColor.CfContract
import FourColor.Patch
import FourColor.Snip
import FourColor.Sew
import FourColor.RevSnip
import FourColor.GridMap
import FourColor.Cube
import FourColor.Combinatorial
import FourColor.Quiz
import FourColor.QuizTree
import FourColor.Part
import FourColor.Discharge
import FourColor.HubCap
import FourColor.RedPart
import FourColor.Birkhoff
import FourColor.QuizData
import FourColor.QuizTreeData
import FourColor.TheQuizTree
import FourColor.Present
import FourColor.Geometry
import FourColor.Grid
import FourColor.Matte
import FourColor.RealPlane
import FourColor.Approx
import FourColor.Finitize
import FourColor.Discretize
import FourColor.FourColorTheorem
import FourColor.Contract
import FourColor.Embed
import FourColor.Present5Defs
import FourColor.Present5Step1
import FourColor.CfReducible
import FourColor.RedpartSound
import FourColor.Unavoidability
import FourColor.Main
import FourColor.RealPlaneMathlib
import FourColor.Complete
import FourColor.Nonvacuity
