#!/usr/bin/env python3
"""Emit `FourColor/Reduce/All.lean`: every configuration's reducibility, chained.

A configuration the bulk rule settles lives, with the other bulk
configurations of its group, in `FourColor/Bulk/Cfg/<group>.lean`
(`gen_bulk_jobs.py --group`, groups from `gen_groups.py`); one it does not has
`FourColor/Bulk/Cfg/Hyb<idx>.lean` (`gen_hybt_jobs.py`) with its walk in
`FourColor/Mask/Cfg<idx>.lean`.  The chain is built in blocks so that no
single term nests hundreds of applications deep.

Usage: gen_all.py <hybrid-index-file> --groups <groups-file> [total=633] [block=40]

`<groups-file>` has one line `<group> <idx>...` per group, as `gen_groups.py`
writes it; every bulk configuration must appear in exactly one group.
"""
import os
import sys

args = sys.argv[1:]
groupsfile = None
if '--groups' in args:
    k = args.index('--groups')
    groupsfile = args[k + 1]
    del args[k:k + 2]
if not args or groupsfile is None:
    sys.exit(__doc__)
hyb = set(int(x) for x in open(args[0]).read().split())
total = int(args[1]) if len(args) > 1 else 633
block = int(args[2]) if len(args) > 2 else 40

group_of = {}
for line in open(groupsfile):
    t = line.split()
    if not t:
        continue
    for x in t[1:]:
        assert int(x) not in group_of, f'configuration {x} in two groups'
        group_of[int(x)] = t[0]
missing = [i for i in range(total) if i not in hyb and i not in group_of]
assert not missing, f'bulk configurations in no group: {missing}'


def mod(i):
    if i in hyb:
        return f'FourColor.Bulk.Cfg.Hyb{i:03d}'
    return f'FourColor.Bulk.Cfg.{group_of[i]}'


def thm(i):
    return f'Bulk.{"Hyb" if i in hyb else "Cfg"}{i:03d}.reducible'


def chain(terms):
    t = terms[0]
    for u in terms[1:]:
        t = f'(cat_reducible_range {t} {u})'
    return t


lines = []
imports = []
for i in range(total):
    if mod(i) not in imports:
        imports.append(mod(i))
lines += [f'import {m}' for m in imports]
lines += ['', '/-!', '# All configurations are C-reducible', '',
          f'The {total} per-configuration certificates, chained into one range.  The',
          f'{len(hyb)} configurations with a hybrid (bulk plus residual walk) certificate',
          'have a module each; the rest, with the bulk certificate alone, are grouped into',
          f'{len(imports) - len(hyb)} modules by ring size, so that the kernel checks the',
          'modules independently and in parallel.  Generated by `scripts/gen_all.py`.',
          '-/', '', 'namespace FourColor', '']
blocks = []
for b0 in range(0, total, block):
    b1 = min(total, b0 + block)
    name = f'reducible_block_{b0 // block}'
    blocks.append(name)
    lines.append(f'/-- Configurations {b0} to {b1 - 1} are C-reducible. -/')
    lines.append(f'theorem {name} : ReducibleInRange {b0} {b1} theConfigs :=')
    lines.append(f'  {chain([thm(i) for i in range(b0, b1)])}')
    lines.append('')
lines.append(f'/-- **All {total} configurations are C-reducible.** -/')
lines.append(f'theorem reducible_all : ReducibleInRange 0 {total} theConfigs :=')
lines.append(f'  {chain(blocks)}')
lines += ['', 'end FourColor', '']
os.makedirs('FourColor/Reduce', exist_ok=True)
open('FourColor/Reduce/All.lean', 'w').write('\n'.join(lines))
print(f'All.lean: {total} configurations, {len(hyb)} hybrid, {len(blocks)} blocks')
